# Default network settings
url = "http://localhost:8545"
network = "sokol" # "core" for the main and "sokol" for the test network

# Custom network settings
coreRpcUrl="http://localhost:8541"
sokolRpcUrl="http://localhost:8540"
coreWsUrl="ws://localhost:8451"
sokolWsUrl="ws://localhost:8450"
corePublicRpcUrl="https://core.poa.network"
sokolPublicRpcUrl="https://sokol.poa.network"

# mining-block-test settings
maxRounds = 5

# Sending txs test
addressTxTest1_sokol = "0x...dfcb"
passwordTxTest1_sokol = "password"
addressTxTest2_sokol = "0x...a72"
passwordTxTest2_sokol = "password"

addressTxTest1_core = "0x"
passwordTxTest1_core = "password"
addressTxTest2_core = "0x.."
passwordTxTest2_core = "password"

#Sending txs via public RPC test
keyStorePathPublicRpc1_sokol = "/path/UTC--.."
addressPublicRpc1_sokol = "0x.."
passwordPublicRpc1_sokol = "password"

keyStorePathPublicRpc2_sokol = "/path/UTC--.."
addressPublicRpc2_sokol = "0x.."
passwordPublicRpc2_sokol = "password"

keyStorePathPublicRpc1_core = "/path/UTC--.."
addressPublicRpc1_core = "0x.."
passwordPublicRpc1_core = "password"

keyStorePathPublicRpc2_core = "/path/UTC--.."
addressPublicRpc2_core = "0x.."
passwordPublicRpc2_core = "password"

# Sending txs via Infura test
keyStorePathInfura1_core = "/path/UTC--.."
addressInfura1_core = "0x.."
passwordInfura1_core = "password"

keyStorePathInfura2_core = "/path/UTC--.."
addressInfura2_core = "0x.."
passwordInfura2_core = "password"

# Transaction settings
gasPrice = "1000000000"
simpleTransactionGas = "21000"
simpleTransactionCost = "21000000000000" # equals to gas multipty by gascost: 21000 * 1000000000
amountToSend = "20000000000"
txsNumber = 10

#Block reward settings
miningReward = "1000000000000000000"
emissionFundsAmount = "1000000000000000000"

# Reorgs settings
maxBlocksToSave = 20

#slack
slackWebHookUrl = 'https://hooks.slack.com/services/............token'
channel = 'monitor'

#Monitor
domainName = "http://localhost:3000/"